Hometask 2
qxbx01/teamcity-testing-framework pull request #2
Opened 2024-11-04 16:43 UTC by qxbx01

Added BuildConfigurationTest, BuildConfigurationPage

2024-11-10 21:38 UTC, nobugs-me requested changes
Привет! 

Спасибо за выполнение базового ДЗ! ⚡️

Тест выполнен корректно, но не хватает проверки, что сущность не создалась в негативном тесте. 

Добавь, пожалуйста, и будет Approve 🤝

2024-11-10 21:38 UTC, nobugs-me commented on src/test/java/com/example/teamcity/ui/BuildConfigurationTest.java
> +        softy.assertEquals(errorMessage, "Build configuration name must not be empty", "Error message is not as expected.");
Отлично! Не хватает проверки на уровне API, что сущность не создалась.

2024-11-11 11:51 UTC, qxbx01 commented
Проверка на уровне API добавлена, как было запрошено.

2024-11-13 13:08 UTC, nobugs-me approved these changes

2024-11-22 13:53 UTC, merged